## Disable authentication for the Frank!Console
application.security.console.authentication.type=NONE
application.security.testtool.authentication.type=NONE

NotificationProcessorApi.active=true

## Larva log level — suppresses "Unknown log level found: [null]" warning
larva.logLevel=DEBUG