/*
 * Copyright 2026 Viscosiety B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.viscosiety.ladybug;

import org.wearefrank.ladybug.Checkpoint;
import org.wearefrank.ladybug.Report;
import org.wearefrank.ladybug.storage.database.DatabaseLogStorage;

/**
 * Debug log storage that fills in a human-readable {@code description} for de-identified shareable
 * reports as they are stored, from the {@code sharable} / {@code originId} session keys that
 * {@link StubbedRunner} stamps on such runs. Ordinary reports pass through untouched.
 *
 * <p>The description must be set at store time because it is serialized into the report blob; the
 * debug log storage is append-only, so it cannot be edited afterwards.</p>
 */
public class ShareableReportDescriber extends DatabaseLogStorage {

    @Override
    public void storeWithoutException(Report report) {
        try {
            if (report != null
                    && (report.getDescription() == null || report.getDescription().isBlank())
                    && "true".equals(sessionKey(report, "sharable"))) {
                report.setDescription(buildDescription(report));
            }
        } catch (Exception ignore) {
            // Never block report storage on description enrichment.
        }
        super.storeWithoutException(report);
    }

    private static String buildDescription(Report report) {
        StringBuilder sb = new StringBuilder("De-identified shareable copy");
        String originId = sessionKey(report, "originId");
        if (originId != null && !originId.isBlank()) {
            sb.append(" of source report #").append(originId);
        }
        String name = report.getName();
        if (name != null && !name.isBlank()) {
            sb.append(" (").append(name.replaceFirst("^Pipeline ", "")).append(")");
        }
        sb.append(". PHI removed; regenerated by replaying the de-identified input with all senders stubbed.");
        return sb.toString();
    }

    private static String sessionKey(Report report, String key) {
        if (report.getCheckpoints() == null) {
            return null;
        }
        String checkpointName = "SessionKey " + key;
        for (Checkpoint checkpoint : report.getCheckpoints()) {
            if (checkpointName.equals(checkpoint.getName())) {
                return checkpoint.getMessage();
            }
        }
        return null;
    }
}
