/*
 * Copyright 2026 Viscosiety B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.viscosiety.ladybug;

import org.wearefrank.ladybug.Report;
import org.wearefrank.ladybug.TestTool;
import org.wearefrank.ladybug.metadata.DefaultValueMetadataFieldExtractor;

/**
 * Provenance metadata field: "was this report a replay / synthetic run, or a real production message?"
 *
 * <p>This is a <em>provenance</em> signal (did the message enter through a live listener?), not a
 * "was a sender stubbed?" signal. The two differ exactly on the reject path: a live message that is
 * rejected before any sender and a replayed message that is rejected before any sender look identical
 * at the checkpoint level, yet only the second is synthetic. So detection keys off the one field that
 * every origin sets deterministically — the report's <b>correlation id</b> — instead of scanning
 * checkpoints for a stub marker.</p>
 *
 * <p>Every replay path bypasses the Receiver/Listener and stamps a recognizable correlation-id prefix,
 * while a real production message carries the wire message id (or none):</p>
 *
 * <ul>
 *   <li><b>viscoFlow {@link StubbedRunner}</b> — correlation id {@code stubbed-run-<uuid>}
 *       ({@link StubbedRunner#DEFAULT_CID_PREFIX}).</li>
 *   <li><b>Ladybug native rerun</b> (the ViscoFlow &#x21ba; replay button and the Ladybug UI's own
 *       rerun) — correlation id {@code <name>-<version>-<UID>} generated by
 *       {@code TestTool.getCorrelationId()}, where {@code <name>} is the Ladybug package title with
 *       spaces replaced by underscores (e.g. {@code Ladybug_common-4.1-SNAPSHOT-<UID>}). Matching the
 *       {@code <name>-} prefix is enough; it is derived from {@link TestTool#getName()} so it tracks
 *       whatever the running build reports.</li>
 * </ul>
 *
 * <p>Because the correlation id is a first-class, immutable report field (stored in its own DB column
 * and already part of {@code metadataNames}), this reads it directly — no checkpoint fetch — and is
 * correct regardless of who produced the replay (the Ladybug UI or ViscoFlow), satisfying the
 * requirement to detect replays independent of origin.</p>
 */
public class StubMetadataFieldExtractor extends DefaultValueMetadataFieldExtractor {

    /** viscoFlow synthetic-run correlation-id prefix (see {@link StubbedRunner#DEFAULT_CID_PREFIX}). */
    private static final String STUBBED_RUN_PREFIX = StubbedRunner.DEFAULT_CID_PREFIX;
    /** Fallback used when the Ladybug package title cannot be resolved (mirrors TestTool.getCorrelationId). */
    private static final String LADYBUG_NAME_FALLBACK = "Ladybug";

    private String trueValue = "true";

    public StubMetadataFieldExtractor() {
        name = "stubbed";
        label = "Stubbed";
        defaultValue = "";
    }

    /** Value returned for a synthetic/replayed report (default {@code "true"}). Live reports use {@code defaultValue}. */
    public void setTrueValue(String trueValue) {
        this.trueValue = trueValue;
    }

    @Override
    public Object extractMetadata(Report report) {
        String cid = report.getCorrelationId();
        if (cid != null && (cid.startsWith(STUBBED_RUN_PREFIX) || cid.startsWith(ladybugRerunPrefix()))) {
            return trueValue;
        }
        return defaultValue;
    }

    /**
     * Prefix of correlation ids produced by Ladybug's native rerunner. {@code TestTool.getCorrelationId()}
     * builds {@code <name>-<version>-<UID>} with spaces in {@code <name>} replaced by underscores, so the
     * stable discriminator is {@code <name>-}. Resolved from {@link TestTool#getName()} (guarded, since the
     * package title can be absent) and falls back to {@code "Ladybug-"} exactly as the runner itself does.
     */
    private static String ladybugRerunPrefix() {
        String name;
        try {
            name = TestTool.getName();
        } catch (RuntimeException e) {
            name = null;
        }
        if (name == null || name.isBlank()) {
            name = LADYBUG_NAME_FALLBACK;
        }
        return name.replaceAll(" ", "_") + "-";
    }
}
